version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 271611439738.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mummyk8s:latest .
      - docker tag mummyk8s:latest 271611439738.dkr.ecr.us-east-1.amazonaws.com/mummyk8s:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 271611439738.dkr.ecr.us-east-1.amazonaws.com/mummyk8s:latest
      - printf '[{"name":"mummy","imageUri":"%s"}]' 271611439738.dkr.ecr.us-east-1.amazonaws.com/mummyk8s:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
