version: 0.2

phases:
  pre_build:
    commands:
      - (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin 271611439738.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t mummyk8s .
      - docker tag mummyk8s:latest 271611439738.dkr.ecr.us-east-1.amazonaws.com/mummyk8s:latest
  post_build:
    commands:
      - docker push 271611439738.dkr.ecr.us-east-1.amazonaws.com/mummyk8s:latest
      - printf '[{"name":"mummy","imageUri":"%s"}]' 271611439738.dkr.ecr.us-east-1.amazonaws.com/mummyk8s:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
